"""init

Revision ID: 0077c76a1ca4
Revises: 
Create Date: 2026-07-16 11:39:18.809188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0077c76a1ca4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=True),
    sa.Column('vk_screen_name', sa.String(), nullable=True),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id'),
    sa.UniqueConstraint('vk_id'),
    sa.UniqueConstraint('vk_screen_name')
    )
    op.create_table('subtopics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('attachment', sa.String(), nullable=True),
    sa.Column('topic_id', sa.BigInteger(), nullable=True),
    sa.Column('subtopic_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('(topic_id IS NOT NULL) <> (subtopic_id IS NOT NULL)', name='ck_question_parent'),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_question_subtopic', 'questions', ['subtopic_id'], unique=True, postgresql_where=sa.text('subtopic_id IS NOT NULL'))
    op.create_index('uq_question_topic', 'questions', ['topic_id'], unique=True, postgresql_where=sa.text('topic_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_question_topic', table_name='questions', postgresql_where=sa.text('topic_id IS NOT NULL'))
    op.drop_index('uq_question_subtopic', table_name='questions', postgresql_where=sa.text('subtopic_id IS NOT NULL'))
    op.drop_table('questions')
    op.drop_table('subtopics')
    op.drop_table('users')
    op.drop_table('topics')
    # ### end Alembic commands ###
