"""add cascade

Revision ID: 3c10e7b0ead4
Revises: 621639591f79
Create Date: 2026-08-19 15:00:19.211019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c10e7b0ead4'
down_revision: Union[str, Sequence[str], None] = '621639591f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('questions_subtopic_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'subtopics', ['subtopic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('subtopics_topic_id_fkey'), 'subtopics', type_='foreignkey')
    op.create_foreign_key(None, 'subtopics', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subtopics', type_='foreignkey')
    op.create_foreign_key(op.f('subtopics_topic_id_fkey'), 'subtopics', 'topics', ['topic_id'], ['id'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_subtopic_id_fkey'), 'questions', 'subtopics', ['subtopic_id'], ['id'])
    # ### end Alembic commands ###
