"""rooms

Revision ID: 621639591f79
Revises: 6b562c4e1b92
Create Date: 2026-08-14 00:32:40.868180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621639591f79'
down_revision: Union[str, Sequence[str], None] = '6b562c4e1b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cipher', sa.BigInteger(), nullable=False),
    sa.Column('comfort', sa.String(), nullable=False),
    sa.Column('room_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_assignments_cipher'), 'room_assignments', ['cipher'], unique=True)
    op.add_column('users', sa.Column('cipher', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'users', ['cipher'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'cipher')
    op.drop_index(op.f('ix_room_assignments_cipher'), table_name='room_assignments')
    op.drop_table('room_assignments')
    # ### end Alembic commands ###
