"""support_tickets_fwd

Revision ID: 6b562c4e1b92
Revises: 8ed70e2fbf79
Create Date: 2026-07-27 00:20:24.177445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b562c4e1b92'
down_revision: Union[str, Sequence[str], None] = '8ed70e2fbf79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('source_peer_id', sa.BigInteger(), nullable=False))
    op.add_column('support_tickets', sa.Column('source_conversation_message_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'source_conversation_message_id')
    op.drop_column('support_tickets', 'source_peer_id')
    # ### end Alembic commands ###
