"""support_tickets

Revision ID: 8ed70e2fbf79
Revises: ec915f58430b
Create Date: 2026-07-26 23:20:01.774681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed70e2fbf79'
down_revision: Union[str, Sequence[str], None] = 'ec915f58430b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'TAKEN', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('moderator_vk_id', sa.Integer(), nullable=True),
    sa.Column('moderator_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('uq_question_topic'), table_name='questions', postgresql_where='(topic_id IS NOT NULL)')
    op.drop_constraint(op.f('questions_topic_id_fkey'), 'questions', type_='foreignkey')
    op.drop_column('questions', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('topic_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('questions_topic_id_fkey'), 'questions', 'topics', ['topic_id'], ['id'])
    op.create_index(op.f('uq_question_topic'), 'questions', ['topic_id'], unique=True, postgresql_where='(topic_id IS NOT NULL)')
    op.drop_table('support_tickets')
    # ### end Alembic commands ###
