"""add cascade

Revision ID: ad182610ee1d
Revises: 621639591f79
Create Date: 2026-08-19 14:41:32.558674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad182610ee1d'
down_revision: Union[str, Sequence[str], None] = '621639591f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cipher', sa.BigInteger(), nullable=False),
    sa.Column('comfort', sa.String(), nullable=False),
    sa.Column('room_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_assignments_cipher'), 'room_assignments', ['cipher'], unique=True)
    op.drop_constraint(op.f('questions_subtopic_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'subtopics', ['subtopic_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint('ck_question_parent', 'questions', '(topic_id IS NOT NULL) <> (subtopic_id IS NOT NULL)')
    op.drop_constraint(op.f('subtopics_topic_id_fkey'), 'subtopics', type_='foreignkey')
    op.create_foreign_key(None, 'subtopics', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.add_column('support_tickets', sa.Column('source_peer_id', sa.BigInteger(), nullable=False))
    op.add_column('support_tickets', sa.Column('source_conversation_message_id', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('cipher', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'users', ['cipher'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'cipher')
    op.drop_column('support_tickets', 'source_conversation_message_id')
    op.drop_column('support_tickets', 'source_peer_id')
    op.drop_constraint(None, 'subtopics', type_='foreignkey')
    op.create_foreign_key(op.f('subtopics_topic_id_fkey'), 'subtopics', 'topics', ['topic_id'], ['id'])
    op.drop_constraint('ck_question_parent', 'questions', type_='check')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_subtopic_id_fkey'), 'questions', 'subtopics', ['subtopic_id'], ['id'])
    op.drop_index(op.f('ix_room_assignments_cipher'), table_name='room_assignments')
    op.drop_table('room_assignments')
    # ### end Alembic commands ###
